"use client";

import Link from "next/link";
import { BusFront, Coins, Fuel, Gauge, Map, Newspaper, Settings2, ShieldCheck, Users, Wrench, Zap, ArrowRight } from "lucide-react";

export function TycoonHud({ companyName, gameDay, gameHour, balance, reputation, buses, fuelPrice, occupancy }: { companyName:string; gameDay:number; gameHour:number; balance:string; reputation:number; buses:number; fuelPrice:number; occupancy:number }) {
  return <>
    <style jsx>{`@keyframes drive{from{transform:translateX(-30%)}to{transform:translateX(125%)}}@keyframes glow{50%{opacity:.8;transform:scale(1.08)}}@keyframes pulse{50%{box-shadow:0 0 0 6px rgba(34,197,94,0)}}.drive{animation:drive 16s linear infinite}.drive2{animation:drive 23s linear infinite reverse}.glow{animation:glow 6s ease-in-out infinite}.live{animation:pulse 2s infinite}.gridbg{background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:36px 36px}`}</style>
    <header className="sticky top-2 z-40 overflow-hidden rounded-2xl border border-white/10 bg-[#0b1013]/90 backdrop-blur-xl shadow-2xl">
      <div className="flex items-center gap-2 px-3 py-2.5">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-amber-400 text-black"><BusFront size={20}/></div>
        <div className="mr-auto min-w-0"><div className="text-[8px] font-black tracking-[.25em] text-amber-400">OTOGAR TYCOON</div><div className="truncate text-xs font-bold">{companyName || "Yeni Şirket"}</div></div>
        <Hud label="GÜN" value={String(gameDay).padStart(2,"0")}/><Hud label="SAAT" value={`${String(gameHour).padStart(2,"0")}:00`}/><Hud label="SERİ" value="×1.15" hot/>
        <div className="hidden sm:flex items-center gap-2 rounded-xl border border-emerald-400/20 px-3 py-2"><span className="live h-2 w-2 rounded-full bg-emerald-400"/><span className="text-[9px] font-black tracking-widest text-emerald-400">CANLI</span></div>
        <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 px-3 py-1.5 text-right"><div className="text-[7px] tracking-widest text-stone-600">KASA</div><div className="text-sm font-black text-amber-300">{balance}</div></div>
      </div>
      <nav className="hidden md:flex gap-1 border-t border-white/5 px-2 py-1 text-[9px] font-black tracking-wide text-stone-500"><Nav href="/dashboard" active>GENEL MERKEZ</Nav><Nav href="/expeditions">SEFERLER</Nav><Nav href="/garage">FİLO</Nav><Nav href="/staff">KADRO</Nav><Nav href="/office">MUHASEBE</Nav><Nav href="/map">HARİTA</Nav><Nav href="/terminal">İNŞAAT</Nav></nav>
    </header>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-3">
      <Metric icon={<Coins/>} label="KASA" value={balance} note="Likidite" tone="amber"/><Metric icon={<Users/>} label="YOLCU TALEBİ" value={`${occupancy}%`} note="Canlı yoğunluk" tone="cyan"/><Metric icon={<ShieldCheck/>} label="İTİBAR" value={`${reputation}/100`} note="Şirket güveni" tone="emerald"/><Metric icon={<Fuel/>} label="MAZOT" value={`${fuelPrice} ₺`} note={`${buses} otobüs · filo`} tone="orange"/>
    </div>
  </>;
}

export function TerminalScene({ occupancy }: { occupancy:number }) {
  return <section className="relative mt-3 overflow-hidden rounded-[26px] border border-white/10 bg-[#11171b] shadow-2xl">
    <div className="absolute inset-0 gridbg opacity-40"/><div className="glow absolute -top-20 left-1/3 h-64 w-64 rounded-full bg-cyan-400/10 blur-[90px]"/>
    <div className="relative h-[330px] sm:h-[430px] overflow-hidden">
      <div className="absolute inset-x-0 bottom-[70px] h-[190px] bg-gradient-to-b from-[#29343a] to-[#151c20]"/>
      <div className="absolute bottom-[70px] left-[4%] h-32 w-40 rounded-t-lg border border-white/5 bg-[#20292e]"><Windows count={15}/></div>
      <div className="absolute bottom-[70px] right-[4%] h-40 w-52 rounded-t-lg border border-white/5 bg-[#1c252a]"><div className="absolute left-4 right-4 top-5 flex h-9 items-center justify-center border border-amber-400/20 bg-[#080d10] text-[10px] font-black tracking-[.3em] text-amber-400">OTOGAR</div><Windows count={18}/></div>
      <div className="absolute left-[20%] right-[20%] bottom-[155px] h-20 rounded-t-[26px] border border-white/10 bg-gradient-to-b from-[#465157] to-[#232c31] shadow-xl"><div className="absolute left-8 right-8 top-5 flex h-9 items-center justify-center rounded-md border border-amber-400/20 bg-[#080d10] text-[10px] font-black tracking-[.28em] text-amber-300">ESENLER ŞEHİRLERARASI TERMİNALİ</div></div>
      <div className="drive absolute bottom-[84px] left-0 z-20 w-56 sm:w-72"><Bus label="NEXORA"/></div><div className="drive2 absolute bottom-[112px] left-0 z-10 w-48 opacity-50"><Bus label="ANADOLU"/></div>
      <div className="absolute inset-x-0 bottom-[70px] h-[85px] border-t border-white/10 bg-gradient-to-b from-[#303b40] to-[#171c20]"><div className="absolute inset-x-0 top-4 flex justify-center gap-2 sm:gap-6">{["03","07","11","14","18"].map((p,i)=><div key={p} className={`flex h-10 w-16 sm:w-24 flex-col items-center justify-center rounded-lg border ${i===1?'border-amber-400/60 bg-amber-400/10':'border-white/10 bg-black/20'}`}><span className="text-[7px] text-stone-600">PERON</span><b className={i===1?'text-amber-300':'text-stone-300'}>{p}</b></div>)}</div></div>
      <div className="absolute bottom-[82px] left-[8%] z-30 text-lg opacity-70">👤 🚶 👨‍🦱 👩 👤</div><div className="absolute bottom-[80px] right-[12%] z-30 text-base opacity-60">👨‍👩‍👧 👤 🚶</div>
      <div className="absolute inset-x-0 bottom-0 h-[70px] border-t border-white/10 bg-[#090d10]"><div className="absolute top-8 inset-x-0 border-t border-dashed border-amber-400/20"/></div>
      <div className="absolute left-3 top-3 rounded-xl border border-white/10 bg-black/45 px-3 py-2 backdrop-blur"><div className="flex items-center gap-2"><span className="live h-2 w-2 rounded-full bg-emerald-400"/><b className="text-[9px] tracking-[.18em] text-emerald-300">OTOGAR CANLI</b></div><div className="mt-1 text-[9px] text-stone-500">1987 · vardiya devam ediyor</div></div>
      <div className="absolute right-3 top-3 w-48 rounded-xl border border-amber-400/20 bg-[#090e11]/85 p-3 backdrop-blur"><div className="flex items-center gap-2 text-amber-300"><Gauge size={15}/><b className="text-[9px] tracking-widest">YOĞUNLUK</b></div><div className="mt-2 h-2 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-emerald-400 via-amber-400 to-orange-500" style={{width:`${Math.max(8,occupancy)}%`}}/></div><div className="mt-1 text-right text-[9px] text-stone-500">{occupancy}% doluluk</div></div>
      <div className="absolute bottom-[170px] left-1/2 hidden -translate-x-1/2 rounded-full border border-amber-400/30 bg-amber-950/70 px-4 py-2 text-[9px] font-black tracking-widest text-amber-200 sm:block">PERON 07 · SENİN OYUN ALANIN</div>
    </div>
    <div className="grid grid-cols-3 gap-2 border-t border-white/10 bg-[#0a0f12] p-2 sm:grid-cols-6">{[["/expeditions",<BusFront/>,"SEFERLER"],["/garage",<Wrench/>,"FİLO"],["/staff",<Users/>,"KADRO"],["/office",<Coins/>,"OFİS"],["/map",<Map/>,"HARİTA"],["/terminal",<Settings2/>,"İNŞAAT"]].map(([href,icon,title])=><Link key={href as string} href={href as string} className="group rounded-xl border border-white/5 bg-white/[.025] px-2 py-3 text-center hover:-translate-y-0.5 hover:border-amber-400/30 transition"><div className="mx-auto flex h-8 w-8 items-center justify-center rounded-lg bg-white/5 text-stone-400 group-hover:text-amber-300">{icon}</div><div className="mt-1 text-[8px] font-black tracking-wider text-stone-300">{title as string}</div></Link>)}</div>
  </section>;
}

export function DecisionCard({ href, title, text }: { href:string; title:string; text:string }) { return <Link href={href} className="group relative flex items-center gap-4 overflow-hidden rounded-2xl border border-amber-400/20 bg-gradient-to-r from-[#21180d] to-[#101416] p-4 shadow-xl"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-400 text-black"><Zap size={21} fill="currentColor"/></div><div className="min-w-0 flex-1"><div className="text-[8px] font-black tracking-[.22em] text-amber-400">SONRAKİ HAMLE</div><div className="mt-1 truncate text-base font-black text-amber-50">{title}</div><div className="text-[10px] text-stone-500">{text}</div></div><ArrowRight className="text-amber-400 group-hover:translate-x-1 transition"/></Link> }

export function LiveOperations({ active }: { active:any[] }) { return <section className="rounded-2xl border border-white/10 bg-[#0e1417] p-4"><div className="mb-3 flex items-center justify-between"><div><div className="text-[8px] font-black tracking-[.2em] text-stone-600">OPERASYON MERKEZİ</div><h2 className="mt-1 text-base font-black">Canlı seferler</h2></div><Link href="/expeditions" className="text-[9px] font-black text-amber-400">TÜMÜ →</Link></div>{active.length===0?<div className="rounded-xl border border-dashed border-white/10 p-7 text-center"><BusFront className="mx-auto text-stone-700"/><p className="mt-2 text-xs text-stone-600">Aktif sefer yok.</p><Link href="/expeditions" className="mt-2 inline-block text-xs text-amber-400">Sefer oluştur →</Link></div>:<div className="space-y-2">{active.slice(0,5).map((e)=><div key={e.id} className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-400/10 text-amber-300"><BusFront size={16}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{e.origin} → {e.destination}</div><div className="text-[9px] text-stone-500">{e.status==='filling'?'Peronda doluyor':'Yolda'} · {e.soldTickets}/{e.maxSeats} · {e.ticketPrice} ₺</div></div><div className="w-20"><div className="h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-orange-500" style={{width:`${Math.min(100,e.soldTickets/Math.max(1,e.maxSeats)*100)}%`}}/></div></div></div></div>)}</div>}</section> }

function Hud({label,value,hot=false}:{label:string;value:string;hot?:boolean}){return <div className="hidden xs:block rounded-xl border border-white/5 bg-white/[.025] px-2 py-1.5 text-center"><div className="text-[7px] tracking-widest text-stone-600">{label}</div><b className={`text-[10px] ${hot?'text-orange-300':'text-stone-300'}`}>{value}</b></div>}
function Nav({href,children,active=false}:{href:string;children:React.ReactNode;active?:boolean}){return <Link href={href} className={`rounded-lg px-3 py-1.5 ${active?'bg-amber-400/10 text-amber-300':'hover:bg-white/5 hover:text-stone-200'}`}>{children}</Link>}
function Metric({icon,label,value,note,tone}:{icon:React.ReactNode;label:string;value:string;note:string;tone:'amber'|'cyan'|'emerald'|'orange'}){const c={amber:'border-amber-400/15',cyan:'border-cyan-400/15',emerald:'border-emerald-400/15',orange:'border-orange-400/15'};return <div className={`rounded-2xl border ${c[tone]} bg-white/[.018] p-3`}><div className="flex items-center gap-2 text-stone-500"><span className="text-amber-300">{icon}</span><b className="text-[8px] tracking-[.18em]">{label}</b></div><div className="mt-2 text-lg font-black tabular-nums">{value}</div><div className="text-[9px] text-stone-600">{note}</div></div>}
function Windows({count}:{count:number}){return <div className="grid grid-cols-5 gap-2 p-3 opacity-30">{Array.from({length:count}).map((_,i)=><span key={i} className="h-3 rounded-sm bg-amber-300/50"/>)}</div>}
function Bus({label}:{label:string}){return <svg viewBox="0 0 420 145" className="w-full drop-shadow-[0_15px_18px_rgba(0,0,0,.65)]"><defs><linearGradient id={`g-${label}`} x1="0" x2="1"><stop stopColor="#171d20"/><stop offset=".55" stopColor="#4a5559"/><stop offset="1" stopColor="#171d20"/></linearGradient></defs><rect x="12" y="20" width="396" height="93" rx="20" fill={`url(#g-${label})`} stroke="#9ca3a8" strokeOpacity=".3"/><rect x="30" y="34" width="285" height="38" rx="7" fill="#071014"/><rect x="326" y="36" width="60" height="32" rx="6" fill="#0b1114"/><path d="M28 78H390" stroke="#f59e0b" strokeWidth="3"/><text x="45" y="59" fill="#e2e8f0" fontSize="14" fontWeight="800" letterSpacing="4">{label}</text><text x="334" y="57" fill="#fbbf24" fontSize="9" fontWeight="800">1987</text><circle cx="88" cy="118" r="20" fill="#080b0d" stroke="#667075" strokeWidth="5"/><circle cx="340" cy="118" r="20" fill="#080b0d" stroke="#667075" strokeWidth="5"/><circle cx="88" cy="118" r="7" fill="#cbd5e1"/><circle cx="340" cy="118" r="7" fill="#cbd5e1"/></svg>}
