"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BookOpen, Check, Lock, Newspaper, Route, Shield } from "lucide-react";
import { useGameStore } from "@/store/gameStore";
import { formatMoney } from "@/lib/utils";

const KEY="otogar-story-v1";
type Choice={label:string;desc:string;money?:number;rep?:number;next:string};
type Chapter={id:string;title:string;kicker:string;body:string;unlock:number;choices:Choice[]};
const CHAPTERS:Chapter[]=[
 {id:"first-key",title:"Anahtar",kicker:"BÖLÜM 1 · YAZIHANE",unlock:1,body:"1987. Cebinde sınırlı para, önünde tek bir masa var. Otogarın gürültüsü dışarıda; içeride ise ilk kararın bekliyor. Büyük firma olmak para kadar itibar meselesi.",choices:[{label:"Esnafın sözünü tut",desc:"Kârı düşük ama güveni yüksek bir başlangıç.",money:1800,rep:5,next:"first-key"},{label:"Daha pahalı bilet dene",desc:"İlk gün kasayı büyüt; yolcunun tepkisini göze al.",money:4200,rep:-2,next:"first-key"}]},
 {id:"empty-peron",title:"Boş Peron",kicker:"BÖLÜM 2 · İLK REKABET",unlock:3,body:"Yan peronda yeni bir firma tabela asıyor. Yolcu sayısı aynı, ama onun çığırtkanı daha yüksek sesli. Kavga etmek yerine şirketini nasıl konumlandıracağına karar ver.",choices:[{label:"Hizmete yatırım yap",desc:"Rakibi değil, kendi yolcunu kazan.",money:-2500,rep:8,next:"empty-peron"},{label:"Fiyatla cevap ver",desc:"Kısa vadede yolcu çek; marj daralsın.",money:3500,rep:1,next:"empty-peron"}]},
 {id:"dark-offer",title:"Karanlık Teklif",kicker:"BÖLÜM 3 · KULİS",unlock:6,body:"Akşam bir telefon geliyor. İsim vermeyen biri 'işlerin daha rahat yürümesi' için bir anlaşmadan söz ediyor. Ne yöntem ne de ayrıntı veriliyor; sadece bunun şirketinin geleceğini etkileyebileceğini söylüyor.",choices:[{label:"Uzak dur, kayda geçir",desc:"Temiz defter ve daha güçlü itibar.",money:0,rep:10,next:"dark-offer"},{label:"Teklifi dinle",desc:"Belirsiz bir ortaklık riskini kabul et.",money:7000,rep:-6,next:"dark-offer"}]},
 {id:"national-line",title:"Uzun Hat",kicker:"BÖLÜM 4 · TÜRKİYE",unlock:10,body:"İstanbul-Ankara hattı için fırsat doğuyor. Bir sefer değil, düzenli bir ağ kurmak istiyorsan filonun dayanıklılığı ve kadronun kalitesi önem kazanıyor.",choices:[{label:"Ağı yavaş büyüt",desc:"Daha az risk, daha sağlam şirket.",money:6000,rep:7,next:"national-line"},{label:"Hızlı genişle",desc:"Kasa ve bakım baskısını göze al.",money:14000,rep:-4,next:"national-line"}]},
 {id:"headline",title:"Manşet",kicker:"BÖLÜM 5 · ŞÖHRET",unlock:16,body:"Gazetede şirketinin adı çıkıyor. Artık küçük bir yazıhane değilsin. İnsanlar seni tanıyor; iyi bir gün de kötü bir hata da daha görünür olacak.",choices:[{label:"Hizmeti koru",desc:"Markayı uzun vadeye taşı.",money:12000,rep:10,next:"headline"},{label:"Gösterişe yüklen",desc:"Büyüme hızlansın, itibar daha oynak olsun.",money:20000,rep:-3,next:"headline"}]},
 {id:"empire",title:"Otogar Ağası",kicker:"BÖLÜM 6 · FİNAL",unlock:25,body:"Artık mesele tek bir otobüs değil. Terminal, filo, personel, rakipler ve şehirler aynı masada. Bundan sonrası hikâyenin sonu değil; kendi şirket tarihinin başlangıcı.",choices:[{label:"Ulusal ağ kur",desc:"Büyük hedefe yatırım yap.",money:30000,rep:12,next:"empire"},{label:"Kasayı koru",desc:"Daha temkinli bir imparatorluk kur.",money:15000,rep:5,next:"empire"}]},
];

export default function StoryPage(){
 const state=useGameStore(); const [claimed,setClaimed]=useState<string[]>([]);
 useEffect(()=>{try{setClaimed(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{setClaimed([])}},[]);

 const choose=(c:Chapter,o:Choice)=>{if(claimed.includes(c.id))return; if(o.money&&o.money<0&&!state.spendMoney(-o.money))return; if(o.money&&o.money>0)state.addMoney(o.money); if(o.money)state.addLedger(`Hikâye · ${c.title}`,o.money); if(o.rep)useGameStore.setState(s=>({reputation:Math.max(0,Math.min(100,s.reputation+(o.rep||0)))})); const n=[...claimed,c.id];setClaimed(n);localStorage.setItem(KEY,JSON.stringify(n));state.pushPhone("Yazıhane",`${c.title}: kararın kayda geçti.`);};
 return <main className="min-h-full bg-[#0b0908] text-stone-100 p-4 sm:p-8 pb-28"><div className="max-w-5xl mx-auto">
  <div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><div className="text-[10px] tracking-[.25em] text-amber-500 font-black">1987 · ŞİRKET TARİHİ</div><h1 className="text-3xl font-black mt-1">Hikâye</h1><p className="text-sm text-stone-500 mt-1">Seçimlerin şirketinin para, itibar ve geleceğini değiştirir.</p></div><div className="rounded-2xl border border-amber-900/40 bg-amber-950/20 px-5 py-3"><div className="text-[9px] tracking-widest text-amber-600">İLERLEME</div><div className="text-xl font-black text-amber-300">{claimed.length}/{CHAPTERS.length}</div></div></div>
  <div className="grid lg:grid-cols-3 gap-4"><section className="lg:col-span-2 space-y-3">{CHAPTERS.map(c=>{const open=state.gameDay>=c.unlock,done=claimed.includes(c.id);return <article key={c.id} className={`rounded-2xl border p-5 ${open?"border-amber-900/40 bg-[#15110e]":"border-zinc-900 bg-zinc-950/70 opacity-60"}`}><div className="flex gap-3"><div className={`h-10 w-10 rounded-xl flex items-center justify-center shrink-0 ${done?"bg-emerald-500 text-black":open?"bg-amber-500 text-black":"bg-zinc-800 text-zinc-600"}`}>{done?<Check size={19}/>:open?<BookOpen size={19}/>:<Lock size={18}/>}</div><div className="flex-1"><div className="text-[9px] tracking-widest text-amber-600 font-bold">{c.kicker} · GÜN {c.unlock}+</div><h2 className="text-xl font-black mt-1">{c.title}</h2>{open?<><p className="text-sm text-stone-400 leading-6 mt-2">{c.body}</p><div className="grid sm:grid-cols-2 gap-2 mt-4">{c.choices.map((o,i)=><button key={i} disabled={done} onClick={()=>choose(c,o)} className="text-left rounded-xl border border-zinc-800 bg-black/25 p-3 hover:border-amber-700/50 disabled:opacity-50"><div className="text-sm font-bold text-amber-100">{o.label}</div><div className="text-[11px] text-zinc-500 mt-1">{o.desc}</div><div className="text-[10px] mt-2 text-amber-500">{o.money&&o.money>0?`+${formatMoney(o.money)}`:o.money&&o.money<0?`${formatMoney(o.money)}`:""}{o.rep?` · ${o.rep>0?"+":""}${o.rep} itibar`:""}</div></button>)}</div></>:<p className="text-xs text-zinc-600 mt-2">Bu bölüm Gün {c.unlock}'de açılacak.</p>}</div></div></article>})}</section>
  <aside className="space-y-3"><div className="rounded-2xl border border-cyan-900/30 bg-[#10171b] p-5"><div className="flex items-center gap-2 text-cyan-400"><Newspaper size={17}/><span className="text-[10px] tracking-widest font-bold">DÜNYA</span></div><p className="text-sm text-stone-400 mt-3 leading-6">Her gün gazete, telefon ve yol olayları hikâyeyi canlı tutuyor. Yeni şehirler açıldıkça şirketinin hikâyesi genişliyor.</p></div><div className="rounded-2xl border border-orange-900/30 bg-[#17100c] p-5"><div className="flex items-center gap-2 text-orange-400"><Shield size={17}/><span className="text-[10px] tracking-widest font-bold">KULİS</span></div><p className="text-sm text-stone-400 mt-3">Bazı kararlar temiz kalmayı zorlaştırabilir. Kulis ekranında gelen teklifleri yönet.</p><Link href="/kulis" className="inline-block mt-3 text-xs text-orange-300">Kulis defterini aç →</Link></div><div className="rounded-2xl border border-amber-900/30 bg-[#15110e] p-5"><div className="flex items-center gap-2 text-amber-400"><Route size={17}/><span className="text-[10px] tracking-widest font-bold">SONRAKİ EŞİK</span></div><div className="text-2xl font-black mt-2">Gün {Math.min(...CHAPTERS.filter(c=>c.unlock>state.gameDay).map(c=>c.unlock),state.gameDay)}</div><p className="text-xs text-zinc-500 mt-1">Sefer kur, şirketi büyüt, yeni bölümü aç.</p></div></aside></div>
  <Link href="/dashboard" className="inline-block mt-6 text-xs text-amber-400">← Genel merkeze dön</Link>
 </div></main>;
}
