"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, BookOpen, CheckCircle2, Phone, Shield, Siren } from "lucide-react";
import { BOSS_POOL, useGameStore } from "@/store/gameStore";
import { formatMoney } from "@/lib/utils";

const LOG_KEY="otogar-kulis-log-v1";
export default function KulisPage(){
 const state=useGameStore(); const boss=state.activeBoss; const [log,setLog]=useState<string[]>(()=>{if(typeof window==='undefined')return [];try{return JSON.parse(localStorage.getItem(LOG_KEY)||"[]")}catch{return []}});
 const add=(x:string)=>{const n:[string,...string[]]=[x,...log].slice(0,12) as [string,...string[]];setLog(n);localStorage.setItem(LOG_KEY,JSON.stringify(n));};
 const inspect=()=>{if(!boss){add("Bugün kapıda teklif yok.");return;}const fake=boss.type==="sahte";add(fake?`${boss.bossName}: sahte olduğu anlaşıldı.`:`${boss.bossName}: gerçek baskı. Kararı aceleye getirme.`);state.pushPhone("Kulis Defteri",fake?"Teklif sahte görünüyor.":"Teklif gerçek görünüyor.");};
 const pay=()=>{if(state.payMafia()){add(`${boss?.bossName||"Kulis"}: ödeme yapıldı.`);}};
 const refuse=()=>{if(boss){state.refuseMafia();add(`${boss.bossName}: teklif reddedildi.`);}};
 const known=useMemo(()=>BOSS_POOL.length,[boss]);
 return <main className="min-h-full bg-[#0b0908] text-stone-100 p-4 sm:p-8 pb-28"><div className="max-w-5xl mx-auto">
  <div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><div className="text-[10px] tracking-[.25em] text-orange-500 font-black">OTOGAR KULİSİ · {known} PROFİL</div><h1 className="text-3xl font-black mt-1">Kulis Defteri</h1><p className="text-sm text-stone-500 mt-1">Şirketin karşılaştığı baskıları ve belirsiz teklifleri yönet. Ayrıntılı gerçek dünya yöntemleri yok; sonuçlar oyun ekonomisinde yaşanır.</p></div><Link href="/story" className="text-xs text-amber-400">Hikâyeye dön →</Link></div>
  <div className="grid lg:grid-cols-3 gap-4">
   <section className="lg:col-span-2 rounded-3xl border border-orange-900/40 bg-[#17100c] p-5 sm:p-6 min-h-[360px]">{boss?<><div className="flex items-start justify-between gap-3"><div><div className="text-[9px] tracking-widest text-orange-500 font-bold">KAPI ÇALDI</div><h2 className="text-2xl font-black mt-1">{boss.bossName}</h2><div className="text-xs text-zinc-500 mt-1">{boss.region} · {boss.type==="sahte"?"belirsiz teklif":"yüksek baskı"}</div></div><div className="h-11 w-11 rounded-xl bg-orange-950/50 border border-orange-800/40 flex items-center justify-center"><Phone size={20} className="text-orange-300"/></div></div><div className="mt-6 rounded-2xl border border-zinc-800 bg-black/25 p-4 text-sm leading-7 text-stone-300">“{boss.message}”</div><div className="grid sm:grid-cols-3 gap-2 mt-4"><button onClick={inspect} className="rounded-xl border border-cyan-900/50 bg-cyan-950/20 px-3 py-3 text-left hover:border-cyan-600/60"><BookOpen size={16} className="text-cyan-400"/><div className="text-xs font-bold mt-2">Kulis araştır</div><div className="text-[10px] text-zinc-500 mt-1">Sinyali değerlendir.</div></button><button onClick={pay} className="rounded-xl border border-emerald-900/50 bg-emerald-950/20 px-3 py-3 text-left hover:border-emerald-600/60"><CheckCircle2 size={16} className="text-emerald-400"/><div className="text-xs font-bold mt-2">Öde</div><div className="text-[10px] text-zinc-500 mt-1">{formatMoney(boss.cost)} · kayıtlı gider.</div></button><button onClick={refuse} className="rounded-xl border border-red-900/50 bg-red-950/20 px-3 py-3 text-left hover:border-red-600/60"><Siren size={16} className="text-red-400"/><div className="text-xs font-bold mt-2">Reddet</div><div className="text-[10px] text-zinc-500 mt-1">Sonuçları göze al.</div></button></div></>:<div className="h-full flex flex-col items-center justify-center text-center py-16"><Shield size={38} className="text-emerald-500/70"/><h2 className="text-xl font-black mt-4">Kapı sakin</h2><p className="text-sm text-zinc-500 mt-2 max-w-sm">Yeni bir kulis olayı oyun günleri ilerledikçe çıkabilir. O sırada filonu ve itibarını büyüt.</p></div>}</section>
   <aside className="space-y-3"><div className="rounded-2xl border border-amber-900/30 bg-[#15110e] p-4"><div className="text-[10px] tracking-widest text-amber-500 font-bold">ŞİRKET DURUMU</div><div className="grid grid-cols-2 gap-2 mt-3"><Stat l="Kasa" v={formatMoney(state.balance)}/><Stat l="İtibar" v={`${state.reputation}/100`}/><Stat l="Filo" v={`${state.buses.length}`}/><Stat l="Gün" v={`${state.gameDay}`}/></div></div><div className="rounded-2xl border border-red-900/30 bg-red-950/10 p-4"><div className="flex gap-2 items-center text-red-300"><AlertTriangle size={15}/><span className="text-[10px] tracking-widest font-bold">KURAL</span></div><p className="text-xs text-zinc-500 mt-2 leading-5">Bu sistem tamamen oyun içi kurgu. Gerçek hayatta suç veya tehdit içeren davranışlara yönlendirme yapmaz.</p></div><div className="rounded-2xl border border-zinc-800 bg-zinc-950/70 p-4"><div className="text-[10px] tracking-widest text-zinc-500 font-bold">KULİS KAYITLARI</div><div className="mt-2 space-y-2 max-h-48 overflow-auto">{log.length?log.map((x,i)=><div key={i} className="text-[11px] text-zinc-500 border-b border-zinc-900 pb-2">{x}</div>):<div className="text-xs text-zinc-700">Henüz kayıt yok.</div>}</div></div></aside>
  </div><Link href="/dashboard" className="inline-block mt-6 text-xs text-amber-400">← Genel merkeze dön</Link>
 </div></main>;
}
function Stat({l,v}:{l:string;v:string}){return <div className="rounded-xl bg-black/20 border border-zinc-800 p-2.5"><div className="text-[9px] text-zinc-600">{l}</div><div className="text-sm font-bold text-amber-200 mt-1">{v}</div></div>}
